apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-applications
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - app: monitoring-stack
        path: monitoring/chart
        namespace: monitoring
  template:
    metadata:
      name: '{{app}}'
      labels:
        app: '{{app}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/lucchmielowski/diiage-finals.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
